name: Broken Links Check

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress ${{ inputs.url }}
          fail: true
