name: Lighthouse CI

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: ${{ inputs.url }}
